CC = gcc
CFLAGS = -Wall
RM = rm -rf

all: q1 q2 q3 q4 q8

q1: q1.c
	$(CC) $(CFLAGS) -o q1 q1.c

q2: q2.c
	$(CC) $(CFLAGS) -o q2 q2.c

q3: q3.c
	$(CC) $(CFLAGS) -o q3 q3.c

q4: q4.c
	$(CC) $(CFLAGS) -o q4 q4.c

q8: q8.c
	$(CC) $(CFLAGS) -o q8 q8.c

clean:
	$(RM) q1 q2 q3 q4 q8
	$(RM) *.o
	$(RM) *.output
